### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by rfairooz** [acm-ucr/hsp-website#87]
Create the 404 page, you can design however you want. If you want the bear, you can get it from Figma. 

Make your changes in src/app/not-found.js file

**Comment by kavinphab** [comment]
![image](https://github.com/acm-ucr/hsp-website/assets/29679531/08ac627f-846b-4961-a701-e8c4887dd5e9)
![image](https://github.com/acm-ucr/hsp-website/assets/29679531/eb0a2c43-4bd1-4fd9-8f07-a49aa0f7f948)
